# Generated by Django 4.1.3 on 2022-12-13 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatUser',
        ),
    ]
