# Generated by Django 4.1.3 on 2022-12-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_delete_chatuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('date_added',)},
        ),
        migrations.RemoveField(
            model_name='message',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='text',
        ),
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='message',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True, unique=True),
        ),
    ]
