# Generated by Django 4.1.3 on 2023-01-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_room_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
